### ISSUE TITLE
How to create github-config.json?

### ISSUE THREAD

**Issue by ma8642** [willptswan/git-cli#1]
Hello,

I was so excited to find your medium article since I've been struggling with switching between my two accounts for some time.

## Problem:
After completing all the steps, when I run the command `git-cli config <name>` I get the following error:
```
prompt: What repo are you working on?:  (node:65817) UnhandledPromiseRejectionWarning: Please provide a valid config name (node:65817) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:65817) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:65817) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined
at Object.exports.handler (/Users/marleyalford/code/git-config/src/Push.js:14:35)
.
.
.
```
When I checked Push.js and added a console log, it turned out that the line `const store = new Store({ path: '/Users/marleyalford/git-config.json'});` doesn't successfully retrieve config because I never made a `github-config.json`.

## Questions:
Should I have made a github-config.json file?  (In your tutorial steps, it sounds like this file will be generated on its own.)  If sI need to create it, what should this file contain?

Thanks in advance!

**Comment by willptswan** [comment]
Hi @ma8642,

The config file should have been generated on its own, I am not sure what has gone wrong there.

I would suggest you use Jarvis (https://www.npmjs.com/package/@willptswan/jarvis) instead. I created this repo just for that article so I haven’t worked on it since then. After the article I decided to create a better tool (Jarvis) that has more features. I know the current version of Jarvis has been tested on macOS, Windows, and Linux operating systems with no problems so it should work for you. If not then let me know.

I hope this helps 🙂
